GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTcyNjEwNjUsImV4cCI6MTY5NzI2MTA4MCwiYXVkIjoiNjUyOThhYTg3N2RmY2Q0Mzg2ZjFjYTZhIiwiaXNzIjoic2hhbi5jb20ifQ.o8mLvGLhaPrBy3dILMjL9RBnEkWx194CBnw2f155O6s

### DB
GET https://rn-auth-backend.onrender.com/db

### Login
POST https://rn-auth-backend.onrender.com/auth/login
Content-Type: application/json

{
    "email": "shan@gmail.com",
    "password": "1234"
}

### Login Local
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "shan@gmail.com",
    "password": "1234"
}


### Register
POST https://rn-auth-backend.onrender.com/auth/register
Content-Type: application/json

{
    "email": "shan@gmail.com",
    "password": "1234"
}


###
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2OTcyNjE1MzYsImV4cCI6MTcwMjQ0NTUzNiwiYXVkIjoiNjUyOThhYTg3N2RmY2Q0Mzg2ZjFjYTZhIiwiaXNzIjoic2hhbi5jb20ifQ.fyXefBUonoqygb6ECWwagPPrPvIBKehfi_h-tQoNYJs" 
}

###
DELETE http://localhost:3000/auth/logout


### Get all destinations
GET http://localhost:3000/destinations


### Get destination by id
GET http://localhost:3000/destinations/94fa2844-0d57-4f6a-aa58-db8de8e40f5e